### ISSUE TITLE
Master version on packagist

### ISSUE THREAD

**Issue by diskoremi** [AppVentus/AvAlertifyBundle#19]
Hi,

I'm trying to use your bundle in my app backoffice, but there are a lot of new features like the labels translation in the Master branch.

But I cant reach it from packagist and I cant find how to do this in the documentation.

I got the 2.3 version with packagist and composer.

Thanks

**Comment by lenybernard** [comment]
Sorry for the delay, I just have released a version, this could fix this kind of problem.
